version: '3.7'

services:

  postgres:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 80:80
    volumes: 
      - ./pgadmin:/var/lib/pgadmin

  cloudbeaver:
    image: dbeaver/cloudbeaver:21.1.5
    container_name: cloudbeaver
    ports: 
      - 8978:8978
    volumes: 
      - ./dbeaver/workspace:/opt/cloudbeaver/workspace
