version: '3.7'

services:

  db:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

#  adminer:
#    image: adminer
#    ports:
#      - 8080:8080
    # user: postgres
  
  pgadmin:
    image: dpage/pgadmin4:5.3
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80

